### ISSUE TITLE
Response and Allow-Headers added

### ISSUE THREAD

**Issue by ValeryDubrava** [haproxytech/haproxy-lua-cors#3] opened 2020-03-17 21:49 UTC
Browsers (chrome) respond with errors on CORS method without this line:
```
  txn.http:res_add_header("Access-Control-Allow-Headers", "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With")
    txn.http:res_set_status(200) 
```

**Comment by NickMRamirez** [comment] 2020-05-12 19:49
@ValeryDubrava Can you give more details about how this issue? I am not able to reproduce it.

**Comment by NickMRamirez** [comment] 2020-05-12 19:50
@ValeryDubrava Can you provide more details? I am not able to reproduce this issue.

**Comment by NickMRamirez** [comment] 2020-06-13 19:46
Closing for now, but we can reopen if the problem persists.

**Closed as completed by NickMRamirez** 2020-06-13 19:46 UTC
