### ISSUE TITLE
url rewrite when activated

### ISSUE THREAD

**Issue by highlife22** [haproxytech/haproxy-lua-cors#27] opened 2021-12-01 07:24 UTC
Hello,

HAProxy version 2.5.0-f2e0833 2021/11/23

I have in my conf the lua module for the CORS policy it look like this.

```
global
    lua-load /etc/haproxy/cors.lua
...

defaults
    log global
    option httplog

frontend https_in
    mode http
    bind *:80 v4v6
    bind *:443 v4v6 ssl crt /etc/ssl/certs/cert.pem alpn h2,http/1.1
    acl http      ssl_fc,not
    http-request redirect scheme https if http

    option forwardfor except 127.0.0.1
    http-request add-header X-Forwarded-Proto https
    # Remove a response header
    http-response del-header X-Powered-By

    ######## START CORS ########

    http-request lua.cors "*" "api.domain.com auth.domain.com" "*"
    http-response lua.cors

    ######### END CORS #########

```

If i activate the CORS module i don’t have the CORS policy error but one of my URL is rewrite in a GET call

Before activating the module:
https://api.domain.com/login_check/

After with the module:
https://api.domain.comlogin_check/
missing slash

I don’t understand what is the reason why it remove it.

Thank you for your time and help,

**Comment by NickMRamirez** [comment] 2021-12-02 04:38
One thing stands out as incorrect: Your list of allowed origins should be separated by commas, not spaces. 

Instead of:

```
"api.domain.com auth.domain.com"
```

Use:

```
"api.domain.com,auth.domain.com"
```

There isn't anything in this library that rewrites URLs. Are there other parts of your HAProxy configuration that might be doing that?

**Comment by NickMRamirez** [comment] 2022-01-09 00:12
Closing this issue, since I can not reproduce the issue.

**Closed as completed by NickMRamirez** 2022-01-09 00:12 UTC
